SELECT 
    UPPER(p.DESCRICAO) AS DESCRICAO_PRODUTO,
    TO_CHAR(p.VL_UNITARIO, 'FM999G999G999D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_UNITARIO,
    'VIDRARIA DE LABORATÓRIO' AS TEXTO_LIVRE,
    TO_CHAR(SYSDATE, 'YYYYMM') AS COMPETENCIA
FROM PRODUTO p
WHERE p.CLASSE = 'VIDRARIA DE LABORATÓRIO';
