SELECT 
	UPPER(c.NOME) AS NOME_CLIENTE,
	UPPER(c.NOME_FANTASIA) AS NOME_FANTASIA,
	REPLACE(c.COD_INSCRICAO,'.','') AS COD_INSCRICAO,
	c.COD_CGC_CPF,
	TO_CHAR(c.DT_CADASTRO, 'DD/MM/YYYY') AS DATA_CADASTRO
FROM CLIENTE c
WHERE c.TIPO_PESSOA = 'F';
