SELECT 
    p.ID_PRODUTO, 
    p.DESCRICAO, 
    cp.DESCRICAO AS CLASSE_PRODUTO, 
    SUM(ip.QTD_ITEM) AS QTD_ITEM,
    CASE
        WHEN SUM(ip.QTD_ITEM) > 10 THEN 'A'
        WHEN SUM(ip.QTD_ITEM) BETWEEN 5 AND 10 THEN 'B'
        ELSE 'C'
    END AS CURVA_DE_COMPRA,
    MAX(pe.DT_CRIACAO) AS DATA_ULTIMA_COMPRA
FROM SOSARA.PRODUTO p
JOIN SOSARA.CLASSE_PRODUTO cp ON p.ID_CLASSE = cp.ID_CLASSE
JOIN SOSARA.ITEM_PEDIDO ip ON p.ID_PRODUTO = ip.ID_PRODUTO
JOIN SOSARA.PEDIDO pe ON ip.ID_PEDIDO = pe.ID_PEDIDO
GROUP BY 
    p.ID_PRODUTO, 
    p.DESCRICAO, 
    cp.DESCRICAO
ORDER BY p.DESCRICAO ASC;
