INSERT INTO PEDIDO (ID_CLIENTE, VL_TOTAL, OBSERVACAO, DT_CRIACAO, SN_SITUACAO)
SELECT c.ID_CLIENTE, SUM(ip.VL_TOTAL), 
    CASE p.ID_CLIENTE
        WHEN 7 THEN 'Verificar conta'
        WHEN 8 THEN 'Entregar via Sedex'
        WHEN 9 THEN 'Cliente fixo'
        ELSE 'Cliente fixo'
    END AS OBSERVACAO,
    SYSDATE, 'OK'
FROM CLIENTE c
CROSS JOIN ITEM_PEDIDO ip
INNER JOIN PEDIDO p ON p.ID_PEDIDO = ip.ID_PEDIDO
WHERE c.ID_CLIENTE IN (7,8,9)
GROUP BY c.ID_CLIENTE, p.ID_PEDIDO, p.ID_CLIENTE
HAVING COUNT(ip.ID_PEDIDO) >= 2;
