--Criação da tabela PAÍS
CREATE TABLE PAÍS (
    CODIGO_PAÍS VARCHAR2(3) PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DDI VARCHAR2(3) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS')
);


--Inserção do País BRASIL
INSERT INTO SOSARA.PAÍS (CODIGO_PAÍS, NOME, DDI)
		VALUES (
		'BRA',
		'BRASIL',
		'+55'
);
