--Criação da tabela ESTADOS
CREATE TABLE SOSARA.ESTADOS (
    UF VARCHAR2(3) PRIMARY KEY,
    CODIGO_PAÍS VARCHAR2(3),
    NOME VARCHAR2(100) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'),
    CONSTRAINT fk_ESTADOS_PAÍS FOREIGN KEY (CODIGO_PAÍS) REFERENCES PAÍS(CODIGO_PAÍS)
);


--Inserção dos estados na tabela ESTADOS 
INSERT INTO SOSARA.ESTADOS(UF, CODIGO_PAÍS, NOME)
		  SELECT 'AC', 'BRA', 'Acre' FROM DUAL 
UNION ALL SELECT 'AL', 'BRA', 'Alagoas' FROM DUAL 
UNION ALL SELECT 'AP', 'BRA', 'Amapá' FROM DUAL 
UNION ALL SELECT 'AM', 'BRA', 'Amazonas' FROM DUAL 
UNION ALL SELECT 'BA', 'BRA', 'Bahia' FROM DUAL 
UNION ALL SELECT 'CE', 'BRA', 'Ceará' FROM DUAL 
UNION ALL SELECT 'DF', 'BRA', 'Distrito Federal' FROM DUAL 
UNION ALL SELECT 'ES', 'BRA', 'Espirito Santo' FROM DUAL 
UNION ALL SELECT 'GO', 'BRA', 'Goiás' FROM DUAL 
UNION ALL SELECT 'MA', 'BRA', 'Maranhão' FROM DUAL 
UNION ALL SELECT 'MT', 'BRA', 'Mato Grosso' FROM DUAL 
UNION ALL SELECT 'MS', 'BRA', 'Mato Grosso do Sul' FROM DUAL 
UNION ALL SELECT 'MG', 'BRA', 'Minas Gerais' FROM DUAL 
UNION ALL SELECT 'PA', 'BRA', 'Pará' FROM DUAL 
UNION ALL SELECT 'PB', 'BRA', 'Paraiba' FROM DUAL 
UNION ALL SELECT 'PR', 'BRA', 'Paraná' FROM DUAL 
UNION ALL SELECT 'PE', 'BRA', 'Pernambuco' FROM DUAL 
UNION ALL SELECT 'PI', 'BRA', 'Piauí' FROM DUAL 
UNION ALL SELECT 'RJ', 'BRA', 'Rio de Janeiro' FROM DUAL 
UNION ALL SELECT 'RN', 'BRA', 'Rio Grande do Norte' FROM DUAL 
UNION ALL SELECT 'RS', 'BRA', 'Rio Grande do Sul' FROM DUAL 
UNION ALL SELECT 'RO', 'BRA', 'Rondônia' FROM DUAL 
UNION ALL SELECT 'RR', 'BRA', 'Roraima' FROM DUAL 
UNION ALL SELECT 'SC', 'BRA', 'Santa Catarina' FROM DUAL 
UNION ALL SELECT 'SP', 'BRA', 'São Paulo' FROM DUAL 
UNION ALL SELECT 'SE', 'BRA', 'Sergipe' FROM DUAL 
UNION ALL SELECT 'TO', 'BRA', 'Tocantins' FROM DUAL;
