--Criação da tabela ENDERECO_CLIENTE
CREATE TABLE SOSARA.ENDERECO_CLIENTE (
	ID_ENDERECO NUMBER DEFAULT SEQ_ENDERECO.NEXTVAL PRIMARY KEY,
	ID_CLIENTE NUMBER,
	CEP VARCHAR2(15),
	LOGRADOURO VARCHAR2(100) NOT NULL,
	NUMERO VARCHAR2(10) NOT NULL,
	COMPLEMENTO VARCHAR2(50),
	BAIRRO VARCHAR2(50) NOT NULL,
	CIDADE VARCHAR2(50),
	UF VARCHAR2(3),
	TIPO_ENDERECO CHAR(1) NOT NULL CHECK (TIPO_ENDERECO IN ('P', 'C', 'T')),
	DATA_CADASTRO TIMESTAMP DEFAULT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') NOT NULL,
	OBSERVACAO VARCHAR2(200),
	CONSTRAINT fk_ENDERECO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT fk_ENDERECO_ESTADOS FOREIGN KEY (UF) REFERENCES ESTADOS(UF)
);
