--Criação da Procedure Valor a Pagar dos pedidos 
CREATE OR REPLACE PROCEDURE VALOR_PAGAR(
		ID_CLIENTE IN NUMBER,
		DT_INICIAL IN DATE,
		DT_FINAL IN DATE) IS
    	NOME_CLIENTE CLIENTE.NOME%TYPE;
		COD_PEDIDO PEDIDO.COD_PEDIDO%TYPE;
		xTOTAL_PEDIDO ITEM_PEDIDO.VALOR_TOTAL%TYPE;
BEGIN
    IF DT_FINAL < DT_INICIAL THEN
        DBMS_OUTPUT.PUT_LINE('Data final deve ser maior que data inicial.');
    ELSE
        SELECT C.NOME, P.ID_PEDIDO, SUM(IP.VALOR_TOTAL)
        INTO NOME, ID_PEDIDO, TOTAL_PEDIDO
        FROM CLIENTE C
        JOIN PEDIDO P ON C.ID_CLIENTE = P.ID_CLIENTE
        JOIN ITEM_PEDIDO IP ON P.ID_PEDIDO = IP.ID_PEDIDO
        WHERE C.ID_CLIENTE = ID_CLIENTE AND P.DT_CRIACAO BETWEEN DT_INICIAL AND DT_FINAL
        GROUP BY C.NOME, P.ID_PEDIDO;

        IF TOTAL_PEDIDO IS NULL THEN
            DBMS_OUTPUT.PUT_LINE('Cliente Inexistente ou Sem Pedidos');
        ELSE
            DBMS_OUTPUT.PUT_LINE(NOME_CLIENTE || ', VALOR TOTAL A PAGAR R$ ' || TO_CHAR(TOTAL_PEDIDO));
        END IF;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Cliente Inexistente ou Sem Pedidos');
END;
